### ISSUE TITLE
Chart.bundle.min.js:15 - Uncaught TypeError: Cannot read property '_view' of undefined

### ISSUE THREAD

**Issue by miparnisari** [RafalWilinski/express-status-monitor#4] opened 2016-08-17 17:01 UTC
I'm using the default configurations.

![image](https://cloud.githubusercontent.com/assets/5374887/17745625/f1b6a1c8-6482-11e6-895e-1bb2b42d865f.png)

**Comment by RafalWilinski** [comment] 2016-08-17 19:34
This seems really weird, I wasn't able to reproduce this error. Could you please describe it a bit more? When it's happening (all the time/at the start), etc?

**Comment by arunesh90** [comment] 2016-08-19 13:22
The bug seems to happen for me at very high spikes (Did some stress testing)
![image](https://cloud.githubusercontent.com/assets/5787588/17811001/b8cf6a80-6620-11e6-812a-e2c5b8d6b9fc.png)

**Comment by RafalWilinski** [comment] 2016-09-12 21:55
This will be resolved: https://github.com/RafalWilinski/express-status-monitor/pull/52

**Comment by RafalWilinski** [comment] 2016-09-14 21:11
I think I've fixed that. I'd be glad if someone could confirm that. Version `0.1.3`

**Comment by mattiaerre** [comment] 2016-09-15 02:47
hi @RafalWilinski v0.1.3 still has got that error for me:

"Chart.bundle.min.js:15 Uncaught TypeError: Cannot read property '_view' of undefined"

**Comment by mattiaerre** [comment] 2016-09-15 03:22
hi @RafalWilinski the last Chart.js release fixed this error apparently:

https://github.com/chartjs/Chart.js/releases/tag/v2.2.2

Fixed an issue with drawing a line where all points were skipped #3066

I think we should update the lib to the v2.2.2 as well and close this issue, for the time being, 😄 

// cc @miparnisari @arunesh90

**Comment by mattiaerre** [comment] 2016-09-29 21:34
hi @RafalWilinski shall we close this issue because of the **v0.1.4** release?

**Closed** 2016-09-30 06:38 UTC
Labels: bug, confirmed, in progress
